### ISSUE TITLE
Adding to a plot doesn't update it

### ISSUE THREAD

**Issue by lgatto** [sje30/essgd#2]
1. Produce a plot with `plot(rnorm(100), pch = 19)`
2. Adding a title with `title("My plot")` doesn't update the plot in the essgd buffer
3. Need to navigate to the previous plot and back to see the actual addition to the figure

Also applies to vertical/horizontal lines using `abline()`, adding a grid with `grid()`, or adding a `legend()`.

**Comment by sje30** [comment]
Thanks Laurent.  Can confirm.  I think I have an idea what's going on.

**Comment by lgatto** [comment]
Thanks!

**Comment by sje30** [comment]
I think my change was too simplistic.  Although it fixes your problem, it now always just shows the latest plot; you cannot go back through the history to earlier plots.

I think the solution is to monitor the value of upid from the web socket, which I've to date ignored.

**Comment by sje30** [comment]
I think is sorted now.
